
modLoader = "javafml" #mandatory
loaderVersion = "[46,)"
license = "MIT"

[[mods]] #mandatory
modId = "portableinventory" #mandatory
version = "1.0.0" #mandatory
displayName = "Portable Grid" #mandatory
authors = "Meteorite" #optional
description = "A simple inventory for you"

[[dependencies."portableinventory"]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

[[dependencies."portableinventory"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
